- src: galaxyproject.galaxy
  version: 0.10.11
- src: galaxyproject.nginx
  version: 0.7.1
- src: galaxyproject.postgresql
  version: 1.1.2
- src: galaxyproject.postgresql_objects
  version: 1.2.0
- src: galaxyproject.miniconda
  version: 0.3.1
- src: usegalaxy_eu.certbot
  version: 0.1.9
- src: galaxyproject.gxadmin
  version: 0.0.12
- name: galaxyproject.tusd
  version: 0.0.1
- src: galaxyproject.cvmfs
  version: 0.2.21
- src: usegalaxy_eu.apptainer
  version: 0.0.1
- src: galaxyproject.repos
  version: 0.0.3
- src: galaxyproject.slurm
  version: 1.0.2
- name: usegalaxy_eu.tpv_auto_lint
  version: 0.2.1
- src: geerlingguy.docker
  version: 6.1.0
- src: usegalaxy_eu.rabbitmqserver
  version: 1.4.2
- src: galaxyproject.pulsar
  version: 1.0.10
- name: geerlingguy.redis
  version: 1.8.0
- name: usegalaxy_eu.flower
  version: 1.0.1
- src: usegalaxy_eu.influxdb
  version: v6.0.7
- src: cloudalchemy.grafana
  version: 0.14.2
- src: dj-wasabi.telegraf
  version: 0.12.0
