- src: galaxyproject.galaxy
  version: 0.10.8
- src: galaxyproject.nginx
  version: 0.7.1
- src: galaxyproject.postgresql
  version: 1.1.2
- src: galaxyproject.postgresql_objects
  version: 1.2.0
- src: galaxyproject.miniconda
  version: 0.3.1
- src: usegalaxy_eu.certbot
  version: 0.1.7
- src: galaxyproject.gxadmin
  version: 0.0.8
- name: galaxyproject.tusd
  version: 0.0.1
- src: galaxyproject.cvmfs
  version: 0.2.13
- src: usegalaxy_eu.apptainer
  version: 0.0.1
- src: galaxyproject.repos
  version: 0.0.2
- src: galaxyproject.slurm
  version: 0.1.3
- name: geerlingguy.docker
  version: 6.1.0
- name: usegalaxy_eu.rabbitmqserver
  version: 1.4.1
- src: usegalaxy_eu.influxdb
  version: v6.0.7
- src: cloudalchemy.grafana
  version: 0.14.2
